---
# handlers file for roles/tmux

- name: Link static tmux profile
  become: no
  ansible.builtin.file:
    src: ~bblasco/.tmux/.tmux.conf
    dest: ~bblasco/.tmux.conf
    owner: bblasco
    group: bblasco
    mode: '0644'
    state: link
  listen: update_tmux_profiles

- name: Copy local tmux profile
  become: no
  ansible.builtin.copy:
    remote_src: yes
    src: ~bblasco/.tmux/.tmux.conf.local
    dest: ~bblasco/.tmux.conf.local
    owner: bblasco
    group: bblasco
    mode: '0644'
  listen: update_tmux_profiles
