---
- hosts: cubox
  name: PULL THE FILES REQUIRED FOR POST BUILD INSTALL/CONFIG OF FEDORA LAPTOP
  gather_facts: no
  #become: yes

  tasks:
  - synchronize:
      mode: pull
      src: /home/eblaben/fedora_build/
      dest: /tmp/fedora_build/
    tags:
    - cubox

- hosts: localhost
  connection: local
  name: PERFORM POST BUILD INSTALL/CONFIG OF FEDORA LAPTOP
  gather_facts: yes
  become: yes

  vars:
    # Get the distro major version so we can install
    fedora_version: "{{ ansible_facts['distribution_major_version'] }}"

    regular_packages:
    - p7zip
    - p7zip-plugins
    - unrar
    - icedtea-web
    - java-openjdk
    - gnome-tweak-tool
    - dconf-editor
    - firefox
    - firefox-wayland
    - vlc
    - vim-enhanced
    - clipgrab
    - tigervnc
    - python2-libselinux
    
    redhat_mandatory_packages:
    - SpiderOakGroups

    openvpn_packages:
    - NetworkManager-openvpn
    - NetworkManager-openvpn-gnome

    printer_packages:
    - system-config-printer
    #- devassistant
    #- devassistant-gui

    mp3_packages:
    - gstreamer1-plugins-base
    - gstreamer1-plugins-good
    - gstreamer1-plugins-ugly
    - gstreamer1-plugins-bad-free
    - gstreamer1-plugins-bad-free
    - gstreamer1-plugins-bad-freeworld
    - gstreamer1-plugins-bad-free-extras
    - ffmpeg

    # Consider removing this, refer to section on Gnome Shell extensions below in To Do list
    gnome_shell_extensions_packages:
    # Alternate-tab extension not in Fedora 30
    # - gnome-shell-extension-alternate-tab.noarch
    - gnome-shell-extension-apps-menu.noarch
    - gnome-shell-extension-background-logo.noarch
    - gnome-shell-extension-common.noarch
    - gnome-shell-extension-dash-to-dock.noarch
    - gnome-shell-extension-launch-new-instance.noarch
    - gnome-shell-extension-places-menu.noarch
    - gnome-shell-extension-pomodoro.x86_64
    - gnome-shell-extension-user-theme.noarch
    - gnome-shell-extension-window-list.noarch
    
    flash_packages:
    - gnome-shell-extension-apps-menu.noarch
    - gnome-shell-extension-dash-to-dock.noarch
    - flash-plugin
    - alsa-plugins-pulseaudio
    - libcurl 

  tasks:

  - debug: var=fedora_version

  - name: SET THE SYSTEM HOSTNAME
    hostname:
      name: bblasco-fedora

  #- name: PULL THE REQUIRED FILES VIA RSYNC/SSH
    #synchronize:
      #mode: pull
      #src: eraser215.ddns.net:49152/home/bblasco/fedora_build
      #dest: /tmp/fedora_build

  - name: ENABLE RPM FUSION REPO
    #command: 'dnf install -y http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm'
    command: 'dnf install -y http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm'

  - name: INSTALL REGULAR PACKAGES
    dnf:
      name: "{{ regular_packages }}"
      state: present

      # Force dnf to check if cache is out of date and redownload
      # if needed. Has an effect only if state is present or
      # latest.
      update_cache: yes
 
  #- name: INSTALL RED HAT MANDATORY PACKAGES
    #dnf:
      #name: "{{ redhat_mandatory_packages }}"
      #state: present


   # Pull additional openvpn files/packages down and install as per link below
   # https://redhat.service-now.com/help?id=kb_article&sysparm_article=KB0005424
   # https://redhat.service-now.com/help?id=kb_article&sys_id=5e7dc60713972640daa77b304244b0c4

  - name: INSTALL OPENVPN BINARY PACKAGES
    dnf:
      name: "{{ openvpn_packages }}"
      state: present

  # To be completed
  #- name: INSTALL OPENVPN CONFIGURATION PACKAGES
   # https://redhat.service-now.com/help?id=kb_article&sys_id=5e7dc60713972640daa77b304244b0c4





  - name: INSTALL PRINTER PACKAGES
    dnf:
      name: "{{ printer_packages }}"
      state: present

  - name: CONFIGURE MELBOURNE PRINTER
    lineinfile:
      path: /etc/cups/client.conf
      create: yes
      regexp: '^ServerName'
      line: 'ServerName cups.mel.redhat.com'
      state: present

  # Consider removing this, refer to section on Gnome Shell extensions below in To Do list
  #- name: INSTALL GNOME SHELL EXTENSIONS
  #dnf:
      #name: "{{ gnome_shell_extensions_packages }}"
      #state: present

  - name: INSTALL ADOBE FLASH PACKAGE
    dnf:
      name: http://linuxdownload.adobe.com/adobe-release/adobe-release-x86_64-1.0-1.noarch.rpm
      state: present

  - name: INSTALL ADOBE FLASH GPG KEY
    rpm_key:
      key: /etc/pki/rpm-gpg/RPM-GPG-KEY-adobe-linux

  - name: INSTALL ADDITIONAL FLASH RELATED PACKAGES
    dnf:
      name: "{{ flash_packages }}"
      state: present
      
  - name: DOWNLOAD BLUEJEANS VIDEOCONFERENCING FROM MY PERSONAL DROPBOX
    # Bluejeans RPM retrieved from https://redhat.service-now.com/help?id=kb_article&sys_id=d92b36da4f7d470815cf7f75f110c7ef
    shell: 'cd /tmp && wget https://www.dropbox.com/s/8nt03s5ycy3zh74/bluejeans-1.37.19.x86_64.rpm'

  - name: INSTALL BLUEJEANS VIDEOCONFERENCING
    dnf:
      name: /tmp/bluejeans-1.37.19.x86_64.rpm
      state: present

  - name: INSTALL SIGNAL DESKTOP FROM COPR REPO
    dnf:
      name: signal-desktop
      enablerepo: luminoso/Signal-Desktop
      state: present

  - name: INSTALL JOPLIN NOTES FROM COPR REPO
    dnf:
      name: joplin
      enablerepo: taw/joplin
      state: present


#####################################################################
#
# PREREQUISITES
#
# Install Ansible:
# sudo dnf install ansible python4-dnf
#
# Add bblasco to sudoers file
# bblasco	localhost=(root)	NOPASSWD: /usr/bin/vagrant
#
# Restore your home directory from the remote source
#
# EXECUTION 
#
# ansible-playbook -i hosts build.yml --ask-become-pass --check
# ansible-playbook -i hosts build.yml --ask-become-pass
#
# TASKS TO ADD
#
# Connect to Wifi
# https://redhat.service-now.com/help?id=kb_article&sysparm_article=KB0001616
#
# Configure SpiderOak backups
# https://redhat.service-now.com/help?id=kb_article&sys_id=c09f0e372b66b8004c71dc0e59da15ff
# https://redhat.service-now.com/help?id=kb_article&sysparm_article=KB0000771
#
# Pull additional openvpn files/packages down and install as per link below
# https://redhat.service-now.com/help?id=kb_article&sysparm_article=KB0005424
# https://redhat.service-now.com/help?id=kb_article&sys_id=5e7dc60713972640daa77b304244b0c4
#
# Install appimages
# - NixNote2
# - Other???
#
# Configure the Gnome desktop icons for NixNote2 and anything else i needed to add
#
# Install Signal Desktop from COPR repo
# https://copr.fedorainfracloud.org/coprs/luminoso/Signal-Desktop/
#
# Install Joplin notes from COPR repo
# Copr repo for joplin owned by taw
#
# Install Gnome extensions
# Note that the command below doesn't appear to show all the extensions I have installed.  Why?
# Because not all extensions can be installed as RPMs using DNF
# It turns out you can sync all your gnome extensions using your google account, as per the instructions here:
# https://askubuntu.com/questions/1135175/how-do-i-automatically-reinstall-gnome-shell-extensions-after-reinstalling-ubunt
# 1. Install the Firefox add-on called "GNOME Shell integration"
# 2. Have it sync your extensions for you...?
# 3. Pray
#
# OR install this extension and follow the instructions:
# https://github.com/oae/gnome-shell-extensions-sync
#
# My gist location is:
# https://gist.github.com/eraser215/251271b1c756e28e4149c2ab63d5838c
# My gist token is:
# fafbb4f71f99a6633ba4bd950573db742b23d885
# This appears to be broken somehow
#
# Out of date list:
# dnf list --installed 'gnome-shell-extension*'
# gnome-shell-extension-alternate-tab.noarch
# gnome-shell-extension-apps-menu.noarch
# gnome-shell-extension-background-logo.noarch
# gnome-shell-extension-common.noarch
# gnome-shell-extension-dash-to-dock.noarch
# gnome-shell-extension-launch-new-instance.noarch
# gnome-shell-extension-places-menu.noarch
# gnome-shell-extension-pomodoro.x86_64
# gnome-shell-extension-user-theme.noarch
# gnome-shell-extension-window-list.noarch
#
# Install Chrome extensions
# - Bluejeans Meeting
# - Bluejeans for Google Calendar
# - FoxyProxy Standard
# - Google Calendar
# - Google Docs Offline
# - Google Keep Chrome Extension
# - Open in Firefox
# - KeePass Tusk
# - uBlock Origin
#
# Install Firefox extensions
# - Auto Tab Discard
# - Facebook Containers
# - Firefox Multi Account Containers
# - FoxyProxy Standard
# - Gnome Shell Integration
# - KeePass Tusk
# - Open in Chrome
# - Tab Mover
# - Tree Style Tabs
# - uBlock Origin
#
# Install cockpit
# dnf install cockpit
# systemctl enable cockpit.socket
# systemctl start cockpit
# then connect to localhost:9090
#
# Check the hostname (print output of command below)
# hostnamectl
#
# QUESTIONS/UPDATES REQUIRED
#
# Do I need to install Development tools?
# sudo dnf groupinstall 'Development Tools'
# sudo dnf groupinstall 'C Development Tools and Libraries'
#
# NOTES ON SOME OF THE TASKS COMPLETED
#
# Set the hostname
# hostnamectl set-hostname bblasco_fedora
#
#
#
#
#
#
#####################################################################
