- hosts: localhost
  connection: local

  name: PERFORM CONFIGURATION OF SYSTEM TO RUN MY CONTAINERS
  gather_facts: no
  become: yes

  vars:
  # Explicitly telling Ansible to use Python3, because of the bug below:
  #     # https://github.com/ansible/ansible/issues/54855
  - ansible_python_interpreter: /usr/bin/python3

  tasks:

  - name: Create directory for persistent storage (exported container volumes)
    file:
      path: /var/lib/containers/exported_volumes
      owner: root
      group: root
      mode: '0700'
      state: directory
    tags:
    - storage


  - name: Enable firewall ports for Librespot (Spotify Connect Client) MDNS service (UDP port 5353)
    firewalld:
      service: mdns
      permanent: yes
      state: enabled
    tags:
    - firewall
    - librespot

  - name: Enable firewall ports for Librespot (Spotify Connect Client) TCP high port 49999
    firewalld:
      port: 49999/tcp
      permanent: yes
      state: enabled
    tags:
    - firewall
    - librespot

  - name: Build the Librespot podman container image
    podman_image:
      name: registry.fedoraproject.org/fedora-minimal:32
      path: files/containers/librespot
      build:
        rm: yes
      state: build
      tag: librespot_via_ansible
    register: build_results
    tags:
    - librespot

  - name: Check how my container build went
    debug:
      var: build_results
    - librespot
