- hosts: cubox
  name: PULL THE FILES REQUIRED FOR POST BUILD INSTALL/CONFIG OF FEDORA LAPTOP
  gather_facts: no

  roles:
  - prereqs
  tags:
  - cubox

- hosts: localhost
  connection: local

  name: PERFORM POST BUILD INSTALL/CONFIG OF FEDORA LAPTOP
  gather_facts: yes
  become: yes

  roles:
  - common
  - workstation
  - tmux
  - fedora.linux_system_roles.timesync
  - fedora.linux_system_roles.cockpit
  - fedora.linux_system_roles.podman

