---
# Note: This role is dependent upon the build of librepot as per:
# https://github.com/benblasco/librespot-fedora-buildah
- hosts: nuc.lan
  #connection: local

  name: Install Librespot after jenkins build
  gather_facts: yes
  become: yes

  roles:
  - librespot
