- hosts: localhost
  connection: local

  name: PERFORM CONFIGURATION OF LIBVIRT BASED VIRTUALISATION
  gather_facts: no
  become: yes

  vars:
  # Explicitly telling Ansible to use Python3, because of the bug below:
  #     # https://github.com/ansible/ansible/issues/54855
  - ansible_python_interpreter: /usr/bin/python3

  tasks:

  - name: Create the logical volume on disk for VMs
    lvol:
      vg: fedora
      lv: vm
      size: 300g
    tags:
    - lvm

  - name: Create the filesystem for VMs
    filesystem:
      fstype: xfs
      dev: /dev/fedora/vm
    tags:
    - lvm

  - name: Mount the filesystem for VMs
    mount:
      path: /var/lib/libvirt/images
      src: /dev/fedora/vm
      fstype: xfs
      state: mounted
      backup: yes
    tags:
    - lvm

  - name: Create the logical volume on disk for CodeReady Containers
    lvol:
      vg: fedora
      lv: crc
      size: 50g
    tags:
    - lvm
    - crc

  - name: Create the filesystem for CodeReady Containers
    filesystem:
      fstype: xfs
      dev: /dev/fedora/crc
    tags:
    - lvm
    - crc

  - name: Mount the filesystem for CodeReady Containers
    mount:
      path: /home/bblasco/.crc
      src: /dev/fedora/crc
      fstype: xfs
      state: mounted
      backup: yes
    tags:
    - lvm
    - crc

  - name: Enable the Libvirt service
    service:
      name: libvirtd
      enabled: yes
      state: started

  - name: Configure the routed network for VMs
    virt_net:
      command: define
      name: nuc-network
      xml: '{{ lookup("template", "files/libvirt/nuc-network.xml") }}'

#  - name: Deploy Fedora 32 VM
      #virt:
      #command: define
      #xml: '{{ lookup("template", "files/libvirt/f32/f32.xml") }}'
