- hosts: localhost
  connection: local

  name: PERFORM CONFIGURATION OF LIBVIRT BASED VIRTUALISATION
  gather_facts: no
  become: yes

  vars:
  # Explicitly telling Ansible to use Python3, because of the bug below:
  #     # https://github.com/ansible/ansible/issues/54855
  - ansible_python_interpreter: /usr/bin/python3

  tasks:

  - name: Create the logical volume on disk for VMs
    lvol:
      vg: fedora
      lv: vm
      size: 100g
    tags:
    - lvm

  - name: Create the filesystem for VMs
    filesystem:
      fstype: xfs
      dev: /dev/fedora/vm
    tags:
    - lvm

  - name: Mount the filesystem for VMs
    mount:
      path: /var/lib/libvirt/images
      src: /dev/fedora/vm
      fstype: xfs
      state: mounted
      backup: yes
    tags:
    - lvm

  - name: Enable the Libvirt service
    service:
      name: libvirtd
      enabled: yes
      state: started

  - name: Configure the routed network for VMs
    virt_net:
      command: define
      name: nuc-network
      #xml: "files/libvirt/nuc-network.xml"
      # Above command does not work, because the xml parameter is expecting an xml string, not a file name
      # https://stackoverflow.com/questions/25968490/ansible-virt-module-xml-error
      xml: '{{ lookup("template", "files/libvirt/nuc-network.xml") }}'

 
