- hosts: cubox
  name: PULL THE FILES REQUIRED FOR POST BUILD INSTALL/CONFIG OF HPE MICROSERVER
  gather_facts: no

    #roles:
    #- prereqs
    #tags:
    #- cubox

- hosts: micro.lan
  #connection: local

  name: PERFORM POST BUILD INSTALL/CONFIG OF HPE MICROSERVER
  gather_facts: yes
  become: yes

  roles:
  - common
  - server
  - fedora.linux_system_roles.timesync
  - fedora.linux_system_roles.cockpit
  - fedora.linux_system_roles.podman
  - tmux

