- hosts: cubox
  name: PULL THE FILES REQUIRED FOR POST BUILD INSTALL/CONFIG OF HPE MICROSERVER
  gather_facts: no

  roles:
  - prereqs
  tags:
  - cubox

- hosts: localhost
  connection: local

  name: PERFORM POST BUILD INSTALL/CONFIG OF HPE MICROSERVER
  gather_facts: yes
  become: yes

  roles:
  - common
  - server
