---
- name: Perform post build install/config of HPE MicroServer running Fedora via bootc
  hosts: micro.lan
  gather_facts: yes
  become: yes

  roles:
    - ssh_config_bblasco
    #- fedora.linux_system_roles.storage
    - fedora.linux_system_roles.firewall
    - fedora.linux_system_roles.timesync
    - fedora.linux_system_roles.cockpit
    #- fedora.linux_system_roles.podman
    - geerlingguy.nfs
    #- fedora.linux_system_roles.kdump
    - tmux
    #- librespot
...
