# ansible-galaxy collection install linux_system_roles.storage
# then
# cd ~/.ansible/collections/ansible_collections/fedora/linux_system_roles/requirements.yml
# ansible-galaxy collection install -vv -r requirements.yml
- hosts: micro.lan
  #connection: local
  become: yes

  roles:
    - fedora.linux_system_roles.storage
    - geerlingguy.nfs

  tasks:

    - name: Create mount points for media/backups
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      loop:
        - /mnt/sg1
        - /mnt/sg2
        - /mnt/sg3
      tags:
        - nfs

    - name: Mount the filesystem for media/backups
      mount:
        path: /mnt/sg1
        src: LABEL=SEAGATE1
        fstype: ext4
        state: mounted
        backup: yes

    - name: Mount media/backups filesystem from NUC
      mount:
        src: nuc.lan:/mnt/sg2
        path: /mnt/sg2
        opts: x-systemd.after=network-online.target
        state: mounted
        fstype: nfs
      tags:
        - nfs

    - name: Open the appropriate firewall ports for NFS
      firewalld:
        zone: FedoraServer
        service: '{{ item }}'
        permanent: yes
        immediate: yes
        state: enabled
      loop:
        - nfs
        - nfs3 
        - mountd
        - rpc-bind
      tags:
        - nfs

# Fix the SELinux permissions for user container storage as per:
# https://github.com/containers/podman/issues/12812
# https://github.com/containers/podman/issues/3234
# $ sudo semanage fcontext -a -e $HOME/.local/share/containers /mnt/containers
# $ restorecon -R -v /mnt
    - name: Allow users to modify files in their local container storage directories
      community.general.sefcontext:
        #target: '/mnt/containers(/.*)?'
        target: '/mnt/containers'
        # Trying to set seuser is redundant when using SELinux targeted policy
        seuser: unconfined_u
        setype: data_home_t
        state: present
      tags:
      - selinux

    - name: Apply new SELinux file context to filesystem
      #ansible.builtin.command: restorecon -irv /mnt/containers
      ansible.builtin.command: restorecon -iv /mnt/containers
      tags:
      - selinux

# Edit /etc/containers.conf to ensure rootless containers are stored in correct location
# OLD: # rootless_storage_path = "$HOME/.local/share/containers/storage"
# NEW: rootless_storage_path = "/mnt/containers/$USER/storage"
    - name: Ensure that rootless container storage is in the correct directory
      lineinfile:
        path: /etc/containers/storage.conf
        regexp: '^rootless_storage_path'
        insertafter: '^# rootless_storage_path'
        line: rootless_storage_path = "/mnt/containers/$USER/storage"
        backup: yes
      tags:
      - podman
