---
- hosts: nuc.lan
  #connection: local

  name: Perform post build install/config of Intel NUC server
  gather_facts: yes
  become: yes

  vars:
    kdump_path: /mnt/general/crash

  roles:
  - common
  - server
  - container_host
  - tmux
    #- linux-system-roles.kdump
  - librespot
