# ansible-galaxy install linux-system-roles.storage
# then
# cd ~/.ansible/roles/linux-system-roles.storage
# ansible-galaxy collection install -vv -r meta/collection-requirements.yml
---
- hosts: nuc.lan
  #connection: local
  become: yes
  vars:
    #ansible_python_interpreter: /usr/bin/python3

    mount_point_user_containers: /mnt/containers
    mount_point_root_containers: /var/lib/containers
    mount_point_crc: /home/bblasco/.crc

    storage_pools:
      - name: fedora_nuc
        disks:
          - nvme0n1p3
        volumes:
          - name: root
            size: "40 GiB"
            fs_type: xfs
            mount_point: /
            state: present
          - name: vm_pool
            size: "100 GiB"
            fs_type: xfs
            mount_point: /var/lib/libvirt/vm-pool
            state: present
          - name: user_containers
            size: "20 GiB"
            fs_type: xfs
            mount_point: "{{ mount_point_user_containers }}"
            state: present
          - name: root_containers
            size: "20 GiB"
            fs_type: xfs
            mount_point: "{{ mount_point_root_containers }}"
            state: present
          - name: crc
            size: "100 GiB"
            fs_type: xfs
            mount_point: "{{ mount_point_crc }}"
            state: present
      - name: vg_samsung1tb
        disks:
          - sda
        volumes:
          - name: lv_general
            size: "300 GiB"
            fs_type: xfs
            mount_point: /mnt/general
            state: present

  roles:
    - fedora.linux_system_roles.storage

  tasks:
    - name: What's the user containers directory?
      debug:
        var: mount_point_user_containers

    - name: Configure storage directory for rootless containers
      block:
        - name: Set correct directory ownership/permissions for rootless container mount point
          file:
            path: "{{ mount_point_user_containers }}"
            state: directory
            owner: root
            group: root
            mode: '0777'

        # Fix the SELinux permissions for user container storage as per:
        # https://github.com/containers/podman/issues/12812
        # https://github.com/containers/podman/issues/3234
        # $ sudo semanage fcontext -a -e $HOME/.local/share/containers /mnt/containers
        # $ restorecon -R -v /mnt
        - name: Allow users to modify files in their local container storage directories
          community.general.sefcontext:
            #target: '/mnt/containers(/.*)?'
            #target: '/mnt/containers'
            target: "{{ mount_point_user_containers }}"
            # Trying to set seuser is redundant when using SELinux targeted policy
            seuser: unconfined_u
            setype: data_home_t
            state: present

        - name: Apply new SELinux file context to filesystem
          #ansible.builtin.command: restorecon -irv /mnt/containers
          ansible.builtin.command: restorecon -iv {{ mount_point_user_containers }}

        # Edit /etc/containers.conf to ensure rootless containers are stored in correct location
        # OLD: # rootless_storage_path = "$HOME/.local/share/containers/storage"
        # NEW: rootless_storage_path = "/mnt/containers/$USER/storage"
        - name: Ensure that rootless container storage is in the correct directory
          lineinfile:
            path: /usr/share/containers/storage.conf
            regexp: '^rootless_storage_path'
            insertafter: '^# rootless_storage_path'
            line: rootless_storage_path = "{{ mount_point_user_containers }}/$USER/storage"
            #owner: root
            #group: root
            #mode: '0644'
            backup: yes
      when: mount_point_user_containers is defined
      tags:
      - podman

    - name: Configure storage directory for OpenShift Local
      block:
        - name: Set correct directory ownership/permissions for CRC mount point
          file:
            path: "{{ mount_point_crc }}"
            state: directory
            owner: bblasco
            group: bblasco
            mode: '0755'

        - name: Set correct SELinux permissions for CRC mount point
          community.general.sefcontext:
            target: "{{ mount_point_crc }}"
            # Trying to set seuser is redundant when using SELinux targeted policy
            # unconfined_u:object_r:user_home_t:s0
            seuser: unconfined_u
            setype: user_home_t
            state: present
          tags:
          - selinux

        - name: Apply new SELinux file context to filesystem
          #ansible.builtin.command: restorecon -irv /mnt/containers
          ansible.builtin.command: restorecon -iv {{ mount_point_crc }}
          tags:
          - selinux
      tags:
      - crc
