---
- hosts: opti.lan
  #connection: local

  name: PERFORM POST BUILD INSTALL/CONFIG OF OPTIPLEX MICRO SERVER
  gather_facts: yes
  become: yes

  vars:
    kdump_path: /mnt/general/crash

  roles:
  - common
  - server
  - container_host
  - fedora.linux_system_roles.timesync
  - fedora.linux_system_roles.cockpit
  #- fedora.linux_system_roles.kdump
  - tmux
