# Use:
# $ ansible-galaxy install -r requirements.yml 
#
# Ansible Galaxy role for configuring host as a hypervisor
# https://galaxy.ansible.com/stackhpc/libvirt-host
- src: stackhpc.libvirt-host

# Ansible Galaxy role to quickly deploy new VMs
# https://galaxy.ansible.com/stackhpc/libvirt-vm
- src: stackhpc.libvirt-vm
