# Pre-requisite: ansible-galaxy collection install community.libvirt
#
- hosts: all

  name: Play around with hostvars
  gather_facts: yes
  #become: yes

  vars:

  tasks:

  - name: Show all the hostvars
    debug:
      var: hostvars[ansible_hostname]['ansible_default_ipv4']['address']

  - name: Just do something when a host is in one group
    debug:
      var: hostvars[ansible_hostname]['ansible_default_ipv4']['gateway']
      var: hostvars[ansible_hostname]['ansible_distribution_version']
    when: "'balancer' in group_names"

  - name: Enable some repo
    become: yes
    yum_repository:
      name: ben_repo
      baseurl: http://example.com/ben_repo
      description: Ben's test repo
      gpgcheck: yes
      gpgkey: http://example.com/ben_repo.gpgkey
    when: "'webserver' in group_names"
