---
- hosts: all

  name: Play around with users and passwords
  gather_facts: yes
  become: yes

  vars:
    talia_password: "{{ 'password123' | password_hash('sha512') }}"

  vars_files:
    - vars/passwords.yml

  tasks:
    - name: Show all the hostvars
      debug:
        var: hostvars[ansible_hostname]['ansible_default_ipv4']['address']
  
    - name: Create talia user and hash the password
      user:
        name: talia
        groups: bblasco
        append: yes
        password: "{{ talia_password }}"

    - name: Create macie user and use password from secrets file
      user:
        name: macie
        groups: bblasco
        append: yes
        password: "{{ macie_password | password_hash('sha512') }}"
