---
# tasks file for roles/workstation

# Set the hostname
# hostnamectl set-hostname bblasco_fedora
# Check the hostname (print output of command below)
# hostnamectl
- name: SET THE SYSTEM HOSTNAME
  hostname:
    #name: bblasco-fedora
    #name: { "ThinkPad Yoga 370": "bblasco_yoga370", "ThinkPad T470s": "bblasco_t470s" }[ansible_facts['product_version']] | default("bblasco_fedora")
    #name: "{{ {"ThinkPad Yoga 370": "bblasco_yoga370", "ThinkPad T470s": "bblasco_t470s" }[ansible_facts['product_version']] | default("bblasco_fedora") }}"
    name: '{{ {"ThinkPad Yoga 370": "bblasco-yoga370", "ThinkPad T470s": "bblasco-t470s" }[system_model] | default("bblasco-fedora") }}'
  tags: hostname

#- name: ENABLE RHEL CSB REPO
   #copy:
   #src: /tmp/fedora_build/rhel7-csb-stage.repo
   #dest: /etc/yum.repos.d/rhel7-csb-stage.repo
   #owner: root
   #group: root
   #mode: '0644'

- name: INSTALL WORKSTATION PACKAGES
  dnf:
    name: "{{ workstation_packages }}"
    state: present

#- name: INSTALL RED HAT MANDATORY PACKAGES FROM CSB REPO
  #dnf:
    #name: "{{ redhat_mandatory_packages }}"
    #state: present

- name: INSTALL RED HAT MANDATORY PACKAGES FROM LOCAL RPMs
  dnf:
    name: "{{ redhat_mandatory_packages }}"
    disable_gpg_check: yes
    state: present

# Pull additional openvpn files/packages down and install as per link below
# https://redhat.service-now.com/help?id=kb_article&sys_id=5e7dc60713972640daa77b304244b0c4
- name: INSTALL OPENVPN BINARY PACKAGES
  dnf:
    name: "{{ openvpn_packages }}"
    disable_gpg_check: yes
    state: present

- name: INSTALL OPENVPN CONFIGURATION PACKAGES FROM LOCAL RPMs
  dnf:
    name: "{{ openvpn_config_packages }}"
    disable_gpg_check: yes
    state: present

- name: INSTALL PRINTER PACKAGES
  dnf:
    name: "{{ printer_packages }}"
    state: present

- name: CONFIGURE MELBOURNE PRINTER
  lineinfile:
    path: /etc/cups/client.conf
    create: yes
    regexp: '^ServerName'
    line: 'ServerName cups.mel.redhat.com'
    state: present

- name: INSTALL POWER MANAGEMENT PACKAGES
  # https://linrunner.de/en/tlp/docs/tlp-linux-advanced-power-management.html
  dnf:
    name: "{{ powermgmt_packages }}"
    state: present
  notify: START POWER MANAGEMENT SERVICES
  tags:
  - power

- name: GET RPM PACKAGE FACTS
  package_facts:
    manager: auto
  tags:
  - power

- name: CHECK POWER MANAGEMENT PACKAGE VERSION
  debug:
    msg: "TLP version {{ ansible_facts.packages['tlp'][0].version }} is installed.  Update your config if it's >=1.3"
    #msg: "TLP version {{ ansible_facts.packages['tlp'] }} is installed.  Update your config if it's >=1.3"
    #msg: "TLP version {{ ansible_facts.packages['tlp'] | length }} is installed.  Update your config if it's >=1.3"
  when: "'tlp' in ansible_facts.packages"
  tags:
  - power

- name: CREATE POWER MANAGEMENT TLP DIRECTORY
  # This is the work around so TLP starts as described here: https://github.com/linrunner/TLP/issues/434
  # mkdir /var/lib/tlp
  # restorecon -vR /var/lib/tlp
  file:
    path: /var/lib/tlp
    owner: root
    group: root
    mode: '0755'
    state: directory
  when: fedora_version | int <= 32
  tags:
  - power

- name: SET POWER MANAGEMENT CPU PERFORMANCE SETTING ON AC POWER
  lineinfile:
    path: /etc/default/tlp
    regexp: '^CPU_HWP_ON_AC'
    line: 'CPU_HWP_ON_AC=performance'
    backup: yes
  notify: RESTART POWER MANAGEMENT SERVICES
  when: fedora_version | int <= 32
  tags:
  - power

- name: SET POWER MANAGEMENT CPU TURBO BOOST ON AC POWER
  lineinfile:
    path: /etc/default/tlp
    regexp: 'CPU_BOOST_ON_AC'
    line: 'CPU_BOOST_ON_AC=1'
    backup: yes
  notify: RESTART POWER MANAGEMENT SERVICES
  when: fedora_version | int <= 32
  tags:
  - power

- name: SET CPU SCALING GOVERNOR TO FOCUS ON PERFORMANCE ON AC POWER
  lineinfile:
    path: /etc/default/tlp
    regexp: 'CPU_SCALING_GOVERNOR_ON_AC'
    line: 'CPU_SCALING_GOVERNOR_ON_AC=performance'
    backup: yes
  notify: RESTART POWER MANAGEMENT SERVICES
  when: fedora_version | int <= 32
  tags:
  - power

# Consider removing this, refer to section on Gnome Shell extensions below in To Do list
#- name: INSTALL GNOME SHELL EXTENSIONS
#dnf:
    #name: "{{ gnome_shell_extensions_packages }}"
    #state: present


- name: INSTALL ADOBE FLASH PACKAGE
  dnf:
    name: http://linuxdownload.adobe.com/adobe-release/adobe-release-x86_64-1.0-1.noarch.rpm
    disable_gpg_check: yes
    state: present
  tags:
  - adobe

- name: INSTALL ADOBE FLASH GPG KEY
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-adobe-linux
  tags:
  - adobe

- name: INSTALL ADDITIONAL FLASH RELATED PACKAGES
  dnf:
    name: "{{ flash_packages }}"
    state: present

- name: INSTALL VIRTUALISATION RELATED PACKAGES
  dnf:
    name: "{{ virt_packages }}"
    state: present
  tags:
  - virt

- name: ADD BLUEJEANS GPG KEY
  rpm_key:
    state: present
    key: https://swdl.bluejeans.com/desktop-app/linux/bluejeans_pubkey.gpg
  tags:
  - bluejeans

- name: INSTALL BLUEJEANS VIDEOCONFERENCING
  dnf:
    name: https://swdl.bluejeans.com/desktop-app/linux/2.19.0/BlueJeans_2.19.0.61.rpm
    state: present
  tags:
  - bluejeans

# Install Zoom conferencing as per instructions at:
# https://us04web.zoom.us/download
- name: ADD ZOOM GPG KEY
  rpm_key:
    state: present
    key: https://us04web.zoom.us/linux/download/pubkey
  tags:
  - zoom

- name: INSTALL ZOOM VIDEOCONFERENCING
  dnf:
    name: https://us04web.zoom.us/client/latest/zoom_x86_64.rpm
    state: present
  tags:
  - zoom

- name: ADD RINGCENTRAL GPG KEY
  rpm_key:
    state: present
    key: http://dn.ringcentral.com/data/web/download/RCMeetings/1210/LinuxPublicKey.pub
  tags:
  - ringcentral

- name: INSTALL RINGCENTRAL VIDEOCONFERENCING
  dnf:
    name: http://dn.ringcentral.com/data/web/download/RCMeetings/1210/RCMeetingsClientSetup.rpm
    state: present
  tags:
  - ringcentral

# Install Microsoft VSCode as per instructions at:
# https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions
- name: ADD MICROSOFT VSCODE GPG KEY
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
  tags:
  - vscode
 
- name: ADD MICROSOFT VSCODE REPO
  yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  tags:
  - vscode

- name: INSTALL MICROSOFT VSCODE
  dnf:
    name: code
    state: latest
  tags:
  - vscode

- name: ENABLE COPR REPOS DUE TO LIMITATION OF DNF MODULE
  command: "dnf copr enable -y {{ item }}"
  #command: "dnf copr enable -y luminoso/Signal-Desktop"
  loop: "{{ copr_repos }}"

# Install Signal Desktop from COPR repo
# https://copr.fedorainfracloud.org/coprs/luminoso/Signal-Desktop/
- name: INSTALL SIGNAL DESKTOP FROM COPR REPO
  dnf:
    name: signal-desktop
    #enablerepo: luminoso/Signal-Desktop
    state: latest

# Install Joplin notes from COPR repo
# Copr repo for joplin owned by taw
# https://copr.fedorainfracloud.org/coprs/taw/joplin/
- name: INSTALL JOPLIN NOTES FROM COPR REPO
  dnf:
    name: joplin
    #enablerepo: taw/joplin
    state: latest
  tags:
  - joplin

# Installation of NixNote2 Evernote client
# https://github.com/robert7/nixnote2
# https://github.com/robert7/nixnote2/releases/tag/continuous
- name: INSTALL NIXNOTE2 APPIMAGE FROM GITHUB
  get_url:
    #url: https://github.com/robert7/nixnote2/releases/download/continuous/NixNote2-x86_64.AppImage
    #url: https://github.com/robert7/nixnote2/releases/download/continuous-develop/NixNote2-x86_64.AppImage
    url:  https://github.com/robert7/nixnote2/releases/download/v2.1.6/NixNote2-qt511-x86_64.AppImage
    dest: /usr/local/bin/NixNote2-x86_64.AppImage
    force: yes
    mode: '0755'
    owner: root
    group: root
  tags:
  - nixnote2

- name: COPY NIXNOTE2 SHORTCUT
  copy:
    src: files/nixnote2/nixnote2.desktop
    dest: /home/bblasco/.local/share/applications/nixnote2.desktop
    owner: bblasco
    group: bblasco
    mode: '0664'
  tags:
  - nixnote2

- name: CREATE DIRECTORIES FOR NIXNOTE2 ICON
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: '0755'
    state: directory
  loop:
  - /usr/share/nixnote2/
  - /usr/share/nixnote2/images
  tags:
  - nixnote2

- name: COPY NIXNOTE2 ICON
  copy:
    src: files/nixnote2/windowIcon.png
    dest: /usr/share/nixnote2/images/windowIcon.png
    owner: root
    group: root
    mode: '0644'
  tags:
  - nixnote2

- name: CREATE .SSH DIRECTORY
  file:
    path: /home/bblasco/.ssh
    owner: bblasco
    group: bblasco
    mode: '0700'
    state: directory
  tags:
  - ssh

- name: CREATE MOUNT POINT (CUBOX SSHFS) DIRECTORY
  file:
    path: /mnt/cubox
    owner: bblasco
    group: bblasco
    mode: '0700'
    state: directory
  tags:
  - ssh

- name: COPY SSH CONFIG AND PRIVATE KEY FILES
  copy:
    src: files/ssh/{{ item }}
    dest: /home/bblasco/.ssh
    owner: bblasco
    group: bblasco
    mode: '0600'
  loop:
    - config
    - id_rsa
    - id_rsa.pub
  tags:
  - ssh

- name: COPY TERMINATOR CONFIG FILE
  copy:
    src: files/terminator/config
    dest: /home/bblasco/.terminator
    owner: bblasco
    group: bblasco
    mode: '0644'

- name: COPY RSYNC FILES
  copy:
    src: files/rsync
    dest: /home/bblasco
    owner: bblasco
    group: bblasco
    mode: '0644'
  tags:
    - rsync

- name: CREATE RSYNC LOG DIRECTORY
  file:
    path: /home/bblasco/rsync_logs
    owner: bblasco
    group: bblasco
    mode: '0755'
    state: directory
  tags:
    - rsync

- name: COPY WIFI INTERFACE FILES
  copy:
    src: "{{ item }}"
    dest: "/etc/sysconfig/network-scripts/"
    owner: root
    group: root
    mode: '0644'
  with_fileglob:
    - "files/wifi/ifcfg*"
  tags:
  - test

- name: COPY ENCRYPTED WIFI KEY FILES
  copy:
    decrypt: yes
    src: "{{ item }}"
    dest: "/etc/sysconfig/network-scripts/"
    owner: root
    group: root
    mode: '0600'
  with_fileglob:
    - "files/wifi/keys_encrypted/*"
  tags:
  - test

- name: REMOVE PACKAGES I DON'T WANT ON THE SYSTEM
  dnf:
    name: "{{ remove_packages }}"
    state: absent
  tags:
  - remove

- name: ADJUST NAUTILUS FILE MANAGER BEHAVIOUR 
  become_user: bblasco
  become: yes
  dconf:
    key: "/org/gnome/nautilus/preferences/always-use-location-entry"
    value: "true"
    state: present
  tags:
  - dconf

# Set Nautilis to show a path that can be copy/pasted
# Set mouse to be left handed
# Change screen idle/lock delay to 10 minutes
- name: CHANGE A BUNCH OF DCONF SETTINGS
  become_user: bblasco
  become: yes
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: "{{ item.state }}"
  loop:
    - { key: "/org/gnome/nautilus/preferences/always-use-location-entry", value: "true", state: "present" }
    - { key: "/org/gnome/desktop/peripherals/mouse/left-handed", value: "true", state: "present" }
    - { key: "/org/gnome/desktop/session/idle-delay", value: "600", state: "present" }
    - { key: "/org/gnome/desktop/interface/show-battery-percentage", value: "true", state: "present" }
  tags:
  - dconf

- name: START OPENSSH SERVER
  service:
    name: "sshd"
    enabled: yes
    state: started
  #when: system_model == "ThinkPad T470s"
  tags:
  - sshd

- name: DISABLE CPU VULNERABILITY MITIGATIONS IN KERNEL
  command: 'grubby --update-kernel=ALL --args="mitigations=off"'
  tags:
  - kernel

- name: ENABLE IP ROUTING SO WE CAN USE IT FOR VIRTUALIZATION ON THINKPAD T470S ONLY
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    reload: yes
  when: system_model == "ThinkPad T470s"
  tags: routing

- name: ENABLE IPv6 FORWARDING WITH RA ROUTES ON WIRELESS INTERFACE SO WE CAN USE IT FOR VIRTUALIZATION ON THINKPAD T470S ONLY
  sysctl:
    name: net.ipv6.conf.wlp58s0.accept_ra
    value: '2'
    sysctl_set: yes
    reload: yes
  when: system_model == "ThinkPad T470s"
  tags: routing
