# ansible-galaxy install stackhpc.libvirt-vm
# Read: https://galaxy.ansible.com/stackhpc/libvirt-vm
# Read: https://github.com/stackhpc/ansible-role-libvirt-vm
- hosts: localhost
  connection: local

  name: Install a VM using a role

  roles:
    - role: stackhpc.libvirt-vm
      libvirt_vms:
        - state: present
          name: 'bblasco-rhel82'
          memory_mb: 4096
          vcpus: 2
          volumes:
            - name: 'bblasco-rhel82'
              device: 'disk'
              #type: 'file'
              format: 'qcow2'
              capacity: '20GB'
              pool: 'vm-pool'
              image: '/var/lib/libvirt/images/rhel-8.2-x86_64-kvm.qcow2'
            - name: 'generic-seed.qcow2'
              type: 'file'
              device: 'cdrom'
              format: 'raw'
              image: '/var/lib/libvirt/images/generic-seed.qcow2'
          interfaces:
            - network: 'vm-network-routed'
