# ansible-galaxy install linux-system-roles.storage
# then
# cd ~/.ansible/roles/linux-system-roles.storage
# ansible-galaxy collection install -vv -r meta/requirements.yml
- hosts: nuc.lan
  #connection: local
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

    storage_pools:
      - name: vg_samsung1tb
        disks:
          - sda
        volumes:
          - name: lv_general
            size: "300 GiB"
            fs_type: xfs
            mount_point: /mnt/general
            state: present
  roles:
    - fedora.linux_system_roles.storage
