# ansible-galaxy collection install -r requirements.yml
---
- hosts: aap.opti.blasco.id.au
  #connection: local
  #become: yes
  #vars:

  vars_files:
    inventory_vars/variables.yml

  roles:
    - redhat_cop.aap_utilities.aap_setup_download
    - redhat_cop.aap_utilities.aap_setup_prepare
    - redhat_cop.aap_utilities.aap_setup_install
