---
- name: Install the cowsay app
  hosts: all
  become: true

  tasks:
    - name: Grab the cowsay application
      ansible.builtin.unarchive:
        src: https://github.com/Code-Hex/Neo-cowsay/releases/download/v2.0.4/cowsay_2.0.4_Linux_x86_64.tar.gz
        dest: /usr/local/bin
        remote_src: yes
