---
- name: Update fapolicyd for cowsay app
  hosts: all
  become: true

  vars:
    trusted_apps:
      - path: /usr/local/bin/cowsay
        size: 2195456
        checksum: 8adee1c9ecc498d2e136c51fc553b9ecabf0bfff46335f0b9010c821580c022f

  roles:
    - { role: shaneboulden.fapolicyd }
