# Pre-requisite: ansible-galaxy collection install community.libvirt
#
- hosts: all
  become: true

  name: Disconnect Insights and Unregister RHEL VMs

  vars:
  # Explicitly telling Ansible to use Python3, because of the bug below:
  #     # https://github.com/ansible/ansible/issues/54855
  #- ansible_python_interpreter: /usr/bin/python3

  - rhel_version: "{{ ansible_facts['distribution_version'] }}"

    rhc_state: absent

  roles:
    - role: linux-system-roles.rhc
