#
# Instructions based on the following doc:
# https://access.redhat.com/documentation/en-us/red_hat_insights/2021/html-single/red_hat_connector_configuration_guide/index#proc_rhc-setting-up-rhcassembly_rhc-configuring
#
- hosts: all

  name: Install and configure the RHC tool (RHEL 8.6+ only)
  gather_facts: yes
  become: yes

  tasks:
    - name: Print the RHEL version
      debug:
        var: ansible_facts['distribution_version']

    - name: End play for this host if RHEL older than 8.6
      ansible.builtin.meta: end_host
      when:
        - ansible_facts['distribution_version'] is version('8.5', '<=')

    # Only relevant for RHEL 8.0-8.5
    - name: Enable repo and install Ansible (RHEL <=8.5)
      block:
        - name: Enable the Ansible repository (RHEL <= 8.5)
          rhsm_repository:
            name: ansible-2.9-for-rhel-8-x86_64-rpms
            state: enabled
  
        - name: Install Ansible (RHEL <= 8.5)
          dnf:
            name: ansible
            state: present
      when:
        - ansible_facts['distribution_version'] is version('8.5', '<=')
  
    - name: Install ansible-core (RHEL >= 8.6)
      dnf:
        name: ansible-core
        state: present
      when:
        - ansible_facts['distribution_version'] is version('8.6', '>=')
  
    - name: Install rhc required packages
      dnf:
        name:
          - rhc-worker-playbook
          - rhc
        state: present
      #loop:
        #- rhc-worker-playbook
        #- rhc
  
    - name: Enable Red Hat Connector
      command: rhc connect
      register: rhc_result
  
    - name: Show RHC result
      debug:
        var: rhc_result
      tags:
      - debug
