# Pre-requisite: ansible-galaxy collection install community.libvirt
# ansible-playbook rhelconfigure.yml --vault-password-file secret.txt 
#
- hosts: all

  name: Register RHEL VMs and install Insights/related
  gather_facts: yes
  become: yes

  vars_files:
    - vars/rhn_credential.yml
    - vars/ssg_versions.yml
    - vars/rhc_configuration.yml

  vars:
  # Explicitly telling Ansible to use Python3, because of the bug below:
  #     # https://github.com/ansible/ansible/issues/54855
  #- ansible_python_interpreter: /usr/bin/python3

    rhel_version: "{{ ansible_facts['distribution_version'] }}"
      #rhel_version: "{{ ansible_facts['distribution_major_version'] }}"

  pre_tasks:
    - name: Show the RHEL version and scap-security-guide-version
      debug:
        msg: RHEL version {{ rhel_version }} requires {{ scap_security_guide_package[ rhel_version ] }}
      tags:
      - insights
      - debug

    - name: Set the system hostname correctly
      hostname:
        name: "{{ inventory_hostname }}"
        use: systemd
      tags:
        - hostname

    - name: Set the system timezone correctly
      community.general.timezone:
        name: Australia/Melbourne
      tags:
        - timezone

  tasks:

    - name: Run the RHC role
      include_role:
        name: linux-system-roles.rhc
      tags:
        - rhc

    - name: Install some useful packages
      yum:
        name:
          - bash-completion
          - vim
          - tmux
          - git
        state: present

  post_tasks:

    - name: Install specific scap-security-guide package
      yum:
        name:
          # Note that this exact format is needed to dereference rhel_version variable
          # Cannot use scap_security_guide_package.rhel_version notation
          - "{{ scap_security_guide_package[ rhel_version ] }}"
        state: present
      tags:
        - compliance

    - name: Run the Insights Compliance Role (in install only mode)
      include_role:
        name: redhatinsights.insights.compliance
        tasks_from: install
      tags:
        - compliance
