---
- name: Update fapolicyd and install cowsay app
  hosts: all
  become: true

  vars:
    trusted_apps:
    - path: /usr/local/bin/cowsay
      size: 2195456
      checksum: 8adee1c9ecc498d2e136c51fc553b9ecabf0bfff46335f0b9010c821580c022f

  roles:
    - { role: shaneboulden.fapolicyd }


  tasks:
    - name: Grab the cowsay application
      ansible.builtin.unarchive:
        src: https://github.com/Code-Hex/Neo-cowsay/releases/download/v2.0.4/cowsay_2.0.4_Linux_x86_64.tar.gz
        dest: /usr/local/bin
        remote_src: yes
