# Pre-requisite: ansible-galaxy collection install community.libvirt
#
- hosts: all

  name: Disconnect Insights and Unegister RHEL VMs
  gather_facts: yes
  become: yes

  vars:
  # Explicitly telling Ansible to use Python3, because of the bug below:
  #     # https://github.com/ansible/ansible/issues/54855
  #- ansible_python_interpreter: /usr/bin/python3

  - rhel_version: "{{ ansible_facts['distribution_version'] }}"

  tasks:

  - name: Unregister systems running RHEL <=8.5
    block: 
      - name: unregister the Insights Client
        command: insights-client --unregister
        tags:
          - insights
    
      - name: Unregister the systems with subscription-manager
        redhat_subscription:
          state: absent
        tags:
          - subscription-manager
    when:
      - ansible_facts['distribution_version'] is version('8.5', '<=')

  - name: Unregister systems running RHEL >8.5
    block: 
      - name: Disable Red Hat Connector
        command: rhc disconnect
        #register: rhc_result
    when:
      - ansible_facts['distribution_version'] is version('8.5', '>')
