---
# tasks file for roles/server

- name: CONFIGURE MEDIA GROUP
  group:
    name: media
    gid: 1001
    state: present
  tags:
  - users

- name: CONFIGURE MEDIA USER
  user:
    name: media
    uid: 1001
    group: media
    shell: /bin/bash
    comment: Ben's download user
  tags:
  - users

- name: INSTALL STORAGE RELATED PACKAGES
  dnf:
    name: "{{ storage_packages }}"
    state: present
  tags:
  - storage

- name: INSTALL TUNING RELATED PACKAGES
  dnf:
    name: "{{ tuning_packages }}"
    state: present
  tags:
  - tuning

- name: INSTALL JENKINS NODE REQUIRED PACKAGES
  dnf:
    name: "{{ jenkins_node_packages }}"
    state: present
  tags:
  - jenkins

- name: INSTALL COCKPIT AND PLUGIN PACKAGES
  dnf:
    name: "{{ cockpit_packages }}"
    state: present
  tags:
  - cockpit

- name: ENABLE THE TUNED SERVICE
  systemd:
    name: tuned
    enabled: yes
    state: started
  tags:
  - tuning

- name: ENABLE THE COCKPIT SERVICE
  systemd:
    name: cockpit.socket
    enabled: yes
    state: started
  tags:
  - cockpit
