---
# tasks file for roles/server


- name: CONFIGURE MEDIA USER
  user:
    name: media
    uid: 1001
    group: media
    shell: /bin/bash
    comment: Ben's download user
  tags:
  - users

- name: INSTALL STORAGE RELATED PACKAGES
  dnf:
    name: "{{ storage_packages }}"
    state: present
  tags:
  - storage

- name: INSTALL TUNING RELATED PACKAGES
  dnf:
    name: "{{ tuning_packages }}"
    state: present
  tags:
  - tuning

- name: ENABLE THE COCKPIT SERVICE
  systemd:
    name: cockpit.socket
    enabled: yes
    state: started
  tags:
  - cockpit
