---
# tasks file for roles/tmux

- name: CLONE THE TMUX PROFILE GIT REPO
  become: no
  ansible.builtin.git:
    repo: https://github.com/gpakosz/.tmux.git
    dest: /home/bblasco/.tmux
  notify:
  - link_tmux_profile
  - copy_tmux_profile_local
  tags:
  - tmux
