---
# tasks file for roles/common

- name: SHOW THE FEDORA LINUX VERSION
  debug: var=fedora_version

- name: SHOW THE NETWORK INTERFACES
  debug: var=ansible_interfaces

#- debug: var="{{ ansible_facts['ansible_product_version'] }}"
- name: SHOW THE SYSTEM MODEL NAME
  debug:
    #var: "ansible_facts['product_version']"
    var: system_model
  tags:
  - model

- name: SHOW THE RPM FUSION PACKAGE NAMES
  debug:
    var: rpmfusion_packages

- name: ENABLE RPM FUSION REPO
  #command: 'dnf install -y http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm'
  #command: 'dnf install -y http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm'
  dnf:
    name: "{{ rpmfusion_packages }}"
    disable_gpg_check: yes
    state: latest

- name: PERFORM A SYSTEM UPDATE
  dnf:
    name: "*"
    state: latest
    # Force dnf to check if cache is out of date and redownload
    # if needed. Has an effect only if state is present or
    # latest.
    update_cache: yes

- name: CONFIGURE THE MEDIA GROUP
  ansible.builtin.group:
    name: media
    gid: 1001
    state: present
  tags:
  - users

- name: CONFIGURE THE MEDIA USER
  ansible.builtin.user:
    name: media
    uid: 1001
    group: media
    comment: User-created for media files
    state: present
  tags:
  - users

- name: ADD MEDIA GROUP AS SECONDARY GROUP FOR BBLASCO
  ansible.builtin.user:
    name: bblasco
    append: yes
    groups: media
  tags:
  - users

- name: INSTALL COMMON PACKAGES
  dnf:
    name: "{{ common_packages }}"
    state: present

- name: DISABLE CPU VULNERABILITY MITIGATIONS IN KERNEL
  command: 'grubby --update-kernel=ALL --args="mitigations=off"'
  tags:
  - kernel

- name: COPY SCREENRC FILE (SCREEN CONFIGURATION)
  copy:
    src: files/screen/screenrc
    dest: /home/bblasco/.screenrc
    owner: bblasco
    group: bblasco
    mode: '0644'
  tags:
  - screen

- name: COPY ADDITIONAL SYSTEMD JOURNAL CONFIG
  copy:
    src: files/journald.conf.d/persistentlogs.conf
    dest: /etc/systemd/journald.conf.d/
    owner: root
    group: root
    mode: '0644'
  notify:
  - RESTART JOURNALD
  tags:
  - journald

- name: ENSURE JOURNAL LOG DATA DIRECTORY EXISTS
  file:
    path: /var/log/journal
    state: directory
    owner: root
    group: systemd-journal
    # drwxr-sr-x+ 3 root systemd-journal 46 Jun 10 08:50 /var/log/journal/
    mode: u=rwx,g=rxs,o=rx

  notify:
  - RESTART JOURNALD
  tags:
  - journald

