---
# vars file for roles/workstation

# fatal: [localhost]: FAILED! => {"changed": false, "failures": ["No package vlc available.", "No package gstreamer1-libav available.", "No package gstreamer1-plugin-openh264 available.", "No package openh264 available.", "No package dropbox available.", "No package nautilus-dropbox available.", "No package libva-intel-driver available.", "No package vip available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}


    workstation_packages:

      #- icedtea-web
    - java-openjdk
    - gnome-tweak-tool
    - dconf-editor
    - firefox
    - firefox-wayland
    - filezilla
    #- chromium
    - vlc
    - gstreamer1-libav
    - gstreamer1-plugin-openh264
    - openh264
    # Gvim is vim-X11
    - vim-X11
    # Note: Clipgrab is a YouTube video downloader
    #- clipgrab
    - tigervnc
    #- python2-libselinux
    # Note: libxcrypt-compat required for NixNote2 to launch.  Remove in future?
    #- libxcrypt-compat
    - sshfs
    - autofs
    - terminator
    - dropbox
    - nautilus-dropbox
    - pinta
    - xreader
    - pavucontrol # PulseAudio Volume Control
    #- pulseeffects # PulseAudio Sound Effects control for tuning
    - krb5-workstation # for kinit, see https://source.redhat.com/groups/public/groups_blog/configure_idm_and_automate_kerberos_tickets

    # Intel driver for video acceleration via VA-API, may improve videoconference performance
    - libva-intel-driver
    - libva-intel-hybrid-driver
    # The Intel Media Driver for VA-API is a new VA-API user mode driver
    # supporting hardware accelerated decoding, encoding etc.
    - gstreamer1-vaapi
    - libva-utils
    - libcgroup-tools
    # Intel GPU tools aka intel-gpu-tools, so I can run intel_gpu_top
    - igt-gpu-tools
    # Logitech mouse tools
    - piper
    # Logitech webcam tools
    - guvcview
    # vips is a pre-requisite for Signal Desktop as at 20210831
    - vips
    #  AptX Bluetooth support
    - pipewire-codec-aptx
    # Audio playback and recording
    - audacity
    - audacious
    
    # Packages retrieved from:
    # https://redhat.service-now.com/help?id=kb_article&sysparm_article=KB0000771
    # https://hdn.corp.redhat.com/rhel8-csb/repoview/SpiderOakGroups.html
    # If you want to stay up to date and use the the yum repo, use the repo file:
    # rpm --import https://hdn.corp.redhat.com/rhel8-csb/RPM-GPG-KEY-helpdesk
    # yum-config-manager --add-repo https://hdn.corp.redhat.com/rhel8-csb/rhel8-csb.repo
    #redhat_mandatory_packages:
      ##- SpiderOakGroups
      #- /tmp/fedora_build/SpiderOakGroups-7.5.0-1.el7.x86_64.rpm

    # Pull additional openvpn files/packages down and install as per link below
    # https://redhat.service-now.com/help?id=kb_article&sysparm_article=KB0005424
    # https://redhat.service-now.com/help?id=kb_article&sys_id=5e7dc60713972640daa77b304244b0c4
    openvpn_packages:
    - NetworkManager-openvpn
    - NetworkManager-openvpn-gnome

    # Packages from
    # https://hdn.corp.redhat.com/rhel8-csb/repoview/redhat-internal-cert-install.html
    # https://hdn.corp.redhat.com/rhel8-csb/repoview/redhat-internal-NetworkManager-openvpn-profiles.html
    openvpn_config_packages:
    - /tmp/fedora_build/redhat-internal-cert-install-0.1-25.el7.noarch.rpm
    - /tmp/fedora_build/redhat-internal-NetworkManager-openvpn-profiles-0.1-55.el7.noarch.rpm

    printer_packages:
    - system-config-printer
    #- devassistant
    #- devassistant-gui

    mp3_packages:
    - gstreamer1-plugins-base
    - gstreamer1-plugins-good
    - gstreamer1-plugins-ugly
    - gstreamer1-plugins-bad-free
    - gstreamer1-plugins-bad-free
    - gstreamer1-plugins-bad-freeworld
    - gstreamer1-plugins-bad-free-extras
    - ffmpeg

    # Consider removing this, refer to section on Gnome Shell extensions below in To Do list
    gnome_shell_extensions_packages:
    # Alternate-tab extension not in Fedora 30
    # - gnome-shell-extension-alternate-tab.noarch
    - gnome-shell-extension-apps-menu.noarch
    - gnome-shell-extension-background-logo.noarch
    - gnome-shell-extension-common.noarch
    - gnome-shell-extension-dash-to-dock.noarch
    - gnome-shell-extension-launch-new-instance.noarch
    - gnome-shell-extension-places-menu.noarch
    - gnome-shell-extension-pomodoro.x86_64
    - gnome-shell-extension-user-theme.noarch
    - gnome-shell-extension-window-list.noarch
    
    flash_packages:
    - gnome-shell-extension-apps-menu.noarch
    - gnome-shell-extension-dash-to-dock.noarch
    - flash-plugin
    - alsa-plugins-pulseaudio
    - libcurl 

    powermgmt_packages:
    - tlp
    - tlp-rdw

    powermgmt_services:
    - tlp
    - tlp-sleep

    obs_packages:
    - obs-studio
    - v4l2loopback

    flatpak_remotes:
    - { name: 'flathub', remote: 'https://flathub.org/repo/flathub.flatpakrepo' }

    flatpak_apps:
    - com.spotify.Client
    - org.signal.Signal
    #- com.obsproject.Studio

    remove_packages:
    - cheese
    - gnome-contacts
    - gnome-maps
    - rhythmbox
    # Not removing evince due to bug in Ansible with packages that have a number in the name
    # https://github.com/ansible/ansible/issues/64294
    #- evince
    - virtualbox-guest-additions
    - intel-media-driver

    copr_repos:
    - luminoso/Signal-Desktop
    - taw/joplin
    #- sentry/v4l2loopback

    bluejeans_rpm: https://swdl.bluejeans.com/desktop-app/linux/2.30.1/BlueJeans_2.30.1.18.rpm
    bluejeans_gpg_key: https://swdl.bluejeans.com/desktop-app/linux/bluejeans_pubkey.gpg
