---
# tasks file for roles/prereqs

- name: SYNCHRONIZE LOCAL PACKAGES TO BE INSTALLED FROM MY SFTP SERVER
  synchronize:
    mode: pull
    src: /home/eblaben/fedora_build/
    dest: /tmp/fedora_build/
    compress: no
  register: synchronize_output
  tags:
  - cubox

- name: SHOW SYNCHRONIZATION OUTPUT
  debug: var=synchronize_output
