---
# tasks file for roles/prereqs

- name: SYNCHRONIZE LOCAL PACKAGES TO BE INSTALLED FROM MY SFTP SERVER
  synchronize:
    mode: pull
    src: /mnt/sg1/eblaben_backup/fedora_build/
    dest: /tmp/fedora_build/
    compress: no
  register: synchronize_output
  tags:
    - micro
    - remotefiles

- name: SHOW SYNCHRONIZATION OUTPUT
  debug: var=synchronize_output
  tags:
    - micro
    - remotefiles
