---
# vars file for roles/common

    # Explicitly telling Ansible to use Python3, because of the bug below:
    # https://github.com/ansible/ansible/issues/54855
    ansible_python_interpreter: /usr/bin/python3

    # Get the distro major version so we can install the relevant RPMFusion repositories
    fedora_version: "{{ ansible_facts['distribution_major_version'] }}"

    # Get the system model so we can set the right hostname
    system_model: "{{ ansible_facts['product_version'] }}"

    common_packages:
    - p7zip
    - p7zip-plugins
    - unrar
    - vim-enhanced
    - htop
    - openssh-server
    - grubby
    # WPA supplicant is so you can sign in to wifi networks
    - wpa_supplicant
    - screen
    # Midnight Commander, for file manipulation etc.
    - mc
    - tmux

    rpmfusion_packages:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm

    virt_packages:
    - libvirt-client
    - python3-libvirt
    - python3-lxml
    - vagrant
    - python3-psutil
    - virt-install
    - virt-manager-common
    - virt-viewer
    - cloud-utils

    container_packages:
    - podman
    - buildah
    - skopeo
