---
# vars file for roles/common

    # Explicitly telling Ansible to use Python3, because of the bug below:
    # https://github.com/ansible/ansible/issues/54855
    ansible_python_interpreter: /usr/bin/python3

    # Get the distro major version so we can install the relevant RPMFusion repositories
    fedora_version: "{{ ansible_facts['distribution_major_version'] }}"

    # Get the system model so we can set the right hostname
    system_model: "{{ ansible_facts['product_version'] }}"

    common_packages:
    - p7zip
    - p7zip-plugins
    - unrar
    - vim-enhanced
    - htop
    - openssh-server
    - grubby
    - git
    # WPA supplicant is so you can sign in to wifi networks
    - wpa_supplicant
    - screen
    # Midnight Commander, for file manipulation etc.
    - mc
    - smartmontools
    - ansible
    - ansible-lint
    # Package for Ansible when working with Azure
    - python3-requests-oauthlib
    - lm_sensors
    - lm_sensors-sensord
    # Packages required to be a Jenkins node
    - java-11-openjdk
    # Provides "needs-restarting" utility.  "needs-restarting -r" is a handy command
    - dnf-utils
    - setools-console
    - strace
    - ncdu

    rpmfusion_packages:
    - http://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm
    - http://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm
